version: '3'
services:
  nora-api:
    container_name: dev-nora-api
    build: .
    volumes:
      - ~/docker/volumes/udm-fileserver/uploads:/usr/uploads
    networks:
      wireguard:
        ipv4_address: 10.1.1.113
    restart: always
networks:
  wireguard:
    external: true
