version: '3'
services:
  nora-api:
    container_name: nora-api
    build: .
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    volumes:
      - /home/ubuntu/docker/volumes/udm-fileserver/uploads:/data/uploads
      - /home/ubuntu/docker/volumes/nora-api/secrets:/secrets:ro
      - /etc/localtime:/etc/localtime:ro   # Sync timezone with host
      - /etc/timezone:/etc/timezone:ro
    networks:
      wireguard:
    restart: always
    environment:
    #comment
      TZ: America/Sao_Paulo
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URL: ${DISCORD_REDIRECT_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      COOKIE_SECRET: ${COOKIE_SECRET}
      ORIGIN: ${ORIGIN}
      DOMAIN: ${DOMAIN}
      PORT: ${PORT}
      EFI_PIX_CLIENT_ID: ${EFI_PIX_CLIENT_ID}
      EFI_PIX_CLIENT_SECRET: ${EFI_PIX_CLIENT_SECRET}
      EFI_PIX_BASE_URL: ${EFI_PIX_BASE_URL}
      EFI_PIX_CERT_PATH: ${EFI_PIX_CERT_PATH}
      EFI_PIX_CERT_PASSWORD: ${EFI_PIX_CERT_PASSWORD}
      EFI_PIX_KEY: ${EFIT_PIX_KEY}
      PIX_WEBHOOK_SECRET: ${PIX_WEBHOOK_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_IP: ${DATABASE_IP}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE: ${DATABASE}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      SAVE_UNINITIALIZED: ${SAVE_UNINITIALIZED}
      RESAVE: ${RESAVE}
      COOKIE_MAX_AGE: ${COOKIE_MAX_AGE}
      HTTP_ONLY: ${HTTP_ONLY}
      SECURE: ${SECURE}
      SAME_SITE: ${SAME_SITE}
      CREDENTIALS: ${CREDENTIALS}
      CLOUD: ${CLOUD}
      OBSERVABILIDADE_WEBHOOK_URL: ${OBSERVABILIDADE_WEBHOOK_URL}
      OBSERVABILIDADE_WEBHOOK_TIMEOUT_MS: ${OBSERVABILIDADE_WEBHOOK_TIMEOUT_MS}
networks:
  wireguard:
    external: true
