version: '3.8'

services:
  universodomedo:
    container_name: dev-udm
    build: .
    ports:
      - "5173:5173"
    networks:
      wireguard:
        ipv4_address: 10.1.1.115
networks:
  wireguard:
    external: true
