version: '3'
services:
  nora-api:
    container_name: nora-api
    build: .
    environment:
      NODE_ENV: production
    networks:
      wireguard:
        ipv4_address: 10.1.1.110
    restart: always
networks:
  wireguard:
    external: true
