services:
  galadriel:
    container_name: galadriel
    build: .
    environment:
      NODE_ENV: production
    networks:
      wireguard:
        ipv4_address: 10.1.1.118
networks:
  wireguard:
    external: true
