version: '3.8'

services:
  universodomedo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-app
    volumes:
      - ~/docker/volumes/dev-udm:/app
    command: npm run dev
    environment:
      - NODE_ENV=development
